dataformCoreVersion: 3.0.37
defaultProject: dataform-open-source
defaultLocation: us
defaultDataset: dataform_extreme_weather_programming_example
defaultAssertionDataset: dataform_extreme_weather_programming_example_assertions
defaultNotebookRuntimeOptions:
  outputBucket: gs://some-bucket
